const axios = require("axios"); const request = require("request"); const fs = require("fs-extra"); module.exports.config = {
  name: "logo2",
  version: "1.0.1",
  hasPermssion: 0,
  credits: `Réynél`,
  description: "logo maker version 2",                 commandCategory: "logo",
  usages: "[type] [name]",
  cooldowns: 2,
};
module.exports.run = async function ({ api, event, args, Users }) { let { messageID, senderID, threadID } = event; if (args.length < 2) { return api.sendMessage(`ℹ️ | 𝖲𝖾𝗇𝗌𝖾𝗂, 𝗍𝗁𝖺𝗍 𝗂𝗌 𝗂𝗇𝗏𝖺𝗅𝗂𝖽 𝖼𝗈𝗆𝗆𝖺𝗇𝖽 𝖿𝗈𝗋𝗆𝖺𝗍.\n\n𝗨𝘀𝗲: 𝗅𝗈𝗀𝗈 <𝗍𝗒𝗉𝖾> <𝗇𝖺𝗆𝖾>\n\n𝗟𝗼𝗴𝗼 𝗧𝘆𝗽𝗲:\n\n𝗍𝗋𝖺𝗇𝗌𝖿𝗈𝗋𝗆𝖾𝗋\n\n𝖿𝗅𝗈𝗐𝖾𝗋𝗅𝗈𝗀𝗈\n\n𝗁𝖺𝗋𝗋𝗒\n\n𝗀𝗋𝖺𝖿𝖿𝗂𝗍𝗂\n\n𝗈𝗋𝖺𝗇𝗀𝖾\n\n𝗆𝖺𝗀𝗆𝖺\n\n𝖻𝖾𝗋𝗋𝗒`, threadID, messageID); } let type = args[0].toLowerCase(); let name = args.slice(1).join(" "); let pathImg = __dirname + `/cache/${type}_${name}.png`; let apiUrl, message; switch (type) { case "transformer": apiUrl = `https://chards-bot-api.richardretadao1.repl.co/api/textpro/transformer?text=${name}`; message = "[𝗧𝗥𝗔𝗡𝗦𝗙𝗢𝗥𝗠𝗘𝗥] 𝖲𝖾𝗇𝗌𝖾𝗂, 𝗅𝗈𝗀𝗈 𝖼𝗋𝖾𝖺𝗍𝖾𝖽:"; break; case "flowerlogo": apiUrl = `https://chards-bot-api.richardretadao1.repl.co/api/photooxy/flower-typography?text=${name}`; message = "𝖲𝖾𝗇𝗌𝖾𝗂, 𝗅𝗈𝗀𝗈 𝖼𝗋𝖾𝖺𝗍𝖾𝖽:"; break; case "harry": apiUrl = `https://chards-bot-api.richardretadao1.repl.co/api/photooxy/harry-potter?text=${name}`; message = "[𝗛𝗔𝗥𝗥𝗬 𝗣𝗢𝗧𝗧𝗘𝗥] 𝖲𝖾𝗇𝗌𝖾𝗂, 𝗅𝗈𝗀𝗈 𝖼𝗋𝖾𝖺𝗍𝖾𝖽:"; break; case "orange": apiUrl = `https://chards-bot-api.richardretadao1.repl.co/api/textpro/3d-orange-juice?text=${name}`; message = "[𝗢𝗥𝗔𝗡𝗚𝗘] 𝖲𝖾𝗇𝗌𝖾𝗂, 𝗅𝗈𝗀𝗈 𝖼𝗋𝖾𝖺𝗍𝖾𝖽:"; break; case "berry": apiUrl = `https://chards-bot-api.richardretadao1.repl.co/api/textpro/berry?text=${name}`; message = "[𝗕𝗘𝗥𝗥𝗬] 𝖲𝖾𝗇𝗌𝖾𝗂, 𝗅𝗈𝗀𝗈 𝖼𝗋𝖾𝖺𝗍𝖾𝖽:"; break; case "magma": apiUrl = `https://chards-bot-api.richardretadao1.repl.co/api/textpro/magma?text=${name}`; message = "[𝗠𝗔𝗚𝗠𝗔] 𝖲𝖾𝗇𝗌𝖾𝗂, 𝗅𝗈𝗀𝗈 𝖼𝗋𝖾𝖺𝗍𝖾𝖽:"; break; case "graffiti": apiUrl = `https://chards-bot-api.richardretadao1.repl.co/api/textpro/graffiti1?text=${name}`; message = "[𝗚𝗥𝗔𝗙𝗙𝗜𝗧𝗜] 𝖲𝖾𝗇𝗌𝖾𝗂, 𝗅𝗈𝗀𝗈 𝖼𝗋𝖾𝖺𝗍𝖾𝖽:"; break; default: return api.sendMessage(`ℹ️ | 𝖲𝖾𝗇𝗌𝖾𝗂, 𝗍𝗁𝖺𝗍 𝗂𝗌 𝗂𝗇𝗏𝖺𝗅𝗂𝖽 𝗅𝗈𝗀𝗈 𝗍𝗒𝗉𝖾!`, threadID, messageID); } api.sendMessage("⏳ | 𝖢𝗋𝖾𝖺𝗍𝗂𝗇𝗀 𝗌𝖾𝗇𝗌𝖾𝗂, 𝗉𝗅𝖾𝖺𝗌𝖾 𝗐𝖺𝗂𝗍...", threadID, messageID); let response = await axios.get(apiUrl, { responseType: "arraybuffer" }); let logo = response.data; fs.writeFileSync(pathImg, Buffer.from(logo, "utf-8")); return api.sendMessage( { body: message, attachment: fs.createReadStream(pathImg), }, threadID, () => fs.unlinkSync(pathImg), messageID ); };